Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -173,7 +173,6 @@ jobs:
     - name: Run unit and integration tests and generate in-toto link
       run: |
         cd ${{ inputs.service_path }}
-        # Exécuter les tests sans recompiler
         mvn test -DskipTests=false -DskipAssembly=true -DskipSurefire=false
         rm -f ../../tests.*.link
         in-toto-run --step-name tests \
@@ -181,8 +180,8 @@ jobs:
           --products target/site/jacoco/jacoco.xml \
           --key ../../in-toto.key \
           --no-command \
-          --verbose \
-          --link-file ../../tests.d6982dd8.link
+          --verbose
+        mv ../../tests.d6982dd865aeacdd6febd1acbea1730a2476ad55c8d387ef33c0ad3066773e14.link ../../tests.d6982dd8.link || echo "ERROR: Failed to rename link file"
         echo "Content of tests link file:"
         cat ../../tests.d6982dd8.link
         python3 -m json.tool ../../tests.d6982dd8.link || echo "ERROR: Invalid JSON in tests.d6982dd8.link"
